var nodeMailer = require('nodemailer');

module.exports = {

    sendMail: function (data) {

        var transport = new nodeMailer.createTransport({
            host: "smtp.mailtrap.io",
            port: 2525,
            auth: {
                user: "1a2b3c4d5e6f7g", //generated by Mailtrap
                pass: "1a2b3c4d5e6f7g" //generated by Mailtrap
            }
        });


        var mailOptions = {
            from:"innov237@gmail.com",
            to: data['email'],
            subject: 'Contact mail',
            text: data['message'],
            html: '<b>Hey there! </b><br> We love coding...'
        };

        transport.sendMail(mailOptions, (error, info) => {
            if (error) {
                console.log(error);
            }
            console.log('Message sent: %s', info.messageId);
        });
    }
}